2024-03-19 20:41:10 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/waehrungshandel
2024-03-19 20:41:10 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 303, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x642fa0a27f33 <unknown>
#1 0x642fa071fce6 <unknown>
#2 0x642fa076ae48 <unknown>
#3 0x642fa076af01 <unknown>
#4 0x642fa07ae3f4 <unknown>
#5 0x642fa078cedd <unknown>
#6 0x642fa07ab899 <unknown>
#7 0x642fa078cc53 <unknown>
#8 0x642fa075ddb3 <unknown>
#9 0x642fa075e77e <unknown>
#10 0x642fa09ed86b <unknown>
#11 0x642fa09f1885 <unknown>
#12 0x642fa09db181 <unknown>
#13 0x642fa09f2412 <unknown>
#14 0x642fa09bf25f <unknown>
#15 0x642fa0a16528 <unknown>
#16 0x642fa0a16723 <unknown>
#17 0x642fa0a270e4 <unknown>
#18 0x7572bac94ac3 <unknown>

2024-03-19 20:41:14 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/waehrungshandel
2024-03-19 20:41:14 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 303, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x642fa0a27f33 <unknown>
#1 0x642fa071fce6 <unknown>
#2 0x642fa076ae48 <unknown>
#3 0x642fa076af01 <unknown>
#4 0x642fa07ae3f4 <unknown>
#5 0x642fa078cedd <unknown>
#6 0x642fa07ab899 <unknown>
#7 0x642fa078cc53 <unknown>
#8 0x642fa075ddb3 <unknown>
#9 0x642fa075e77e <unknown>
#10 0x642fa09ed86b <unknown>
#11 0x642fa09f1885 <unknown>
#12 0x642fa09db181 <unknown>
#13 0x642fa09f2412 <unknown>
#14 0x642fa09bf25f <unknown>
#15 0x642fa0a16528 <unknown>
#16 0x642fa0a16723 <unknown>
#17 0x642fa0a270e4 <unknown>
#18 0x7572bac94ac3 <unknown>

2024-03-19 20:41:17 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/waehrungshandel
2024-03-19 20:41:17 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 303, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x642fa0a27f33 <unknown>
#1 0x642fa071fce6 <unknown>
#2 0x642fa076ae48 <unknown>
#3 0x642fa076af01 <unknown>
#4 0x642fa07ae3f4 <unknown>
#5 0x642fa078cedd <unknown>
#6 0x642fa07ab899 <unknown>
#7 0x642fa078cc53 <unknown>
#8 0x642fa075ddb3 <unknown>
#9 0x642fa075e77e <unknown>
#10 0x642fa09ed86b <unknown>
#11 0x642fa09f1885 <unknown>
#12 0x642fa09db181 <unknown>
#13 0x642fa09f2412 <unknown>
#14 0x642fa09bf25f <unknown>
#15 0x642fa0a16528 <unknown>
#16 0x642fa0a16723 <unknown>
#17 0x642fa0a270e4 <unknown>
#18 0x7572bac94ac3 <unknown>

2024-03-19 20:41:20 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/waehrungshandel
2024-03-19 20:41:20 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 303, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x642fa0a27f33 <unknown>
#1 0x642fa071fce6 <unknown>
#2 0x642fa076ae48 <unknown>
#3 0x642fa076af01 <unknown>
#4 0x642fa07ae3f4 <unknown>
#5 0x642fa078cedd <unknown>
#6 0x642fa07ab899 <unknown>
#7 0x642fa078cc53 <unknown>
#8 0x642fa075ddb3 <unknown>
#9 0x642fa075e77e <unknown>
#10 0x642fa09ed86b <unknown>
#11 0x642fa09f1885 <unknown>
#12 0x642fa09db181 <unknown>
#13 0x642fa09f2412 <unknown>
#14 0x642fa09bf25f <unknown>
#15 0x642fa0a16528 <unknown>
#16 0x642fa0a16723 <unknown>
#17 0x642fa0a270e4 <unknown>
#18 0x7572bac94ac3 <unknown>