2024-02-03 08:03:31 ERROR Elements not present after 0.5 seconds on page: https://capital.com/zh/trade-stellar
2024-02-03 08:03:31 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55fc1537dd93 <unknown>
#1 0x55fc15061337 <unknown>
#2 0x55fc150acd60 <unknown>
#3 0x55fc150ace51 <unknown>
#4 0x55fc150f0bc4 <unknown>
#5 0x55fc150cf46d <unknown>
#6 0x55fc150ee12d <unknown>
#7 0x55fc150cf1e3 <unknown>
#8 0x55fc1509f135 <unknown>
#9 0x55fc150a013e <unknown>
#10 0x55fc15341e4b <unknown>
#11 0x55fc15345dfa <unknown>
#12 0x55fc1532e6d5 <unknown>
#13 0x55fc15346a6f <unknown>
#14 0x55fc1531269f <unknown>
#15 0x55fc1536b098 <unknown>
#16 0x55fc1536b262 <unknown>
#17 0x55fc1537cf34 <unknown>
#18 0x7f5f2e094ac3 <unknown>

2024-02-03 08:03:34 ERROR Elements not present after 0.5 seconds on page: https://capital.com/zh/trade-stellar
2024-02-03 08:03:34 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55fc1537dd93 <unknown>
#1 0x55fc15061337 <unknown>
#2 0x55fc150acd60 <unknown>
#3 0x55fc150ace51 <unknown>
#4 0x55fc150f0bc4 <unknown>
#5 0x55fc150cf46d <unknown>
#6 0x55fc150ee12d <unknown>
#7 0x55fc150cf1e3 <unknown>
#8 0x55fc1509f135 <unknown>
#9 0x55fc150a013e <unknown>
#10 0x55fc15341e4b <unknown>
#11 0x55fc15345dfa <unknown>
#12 0x55fc1532e6d5 <unknown>
#13 0x55fc15346a6f <unknown>
#14 0x55fc1531269f <unknown>
#15 0x55fc1536b098 <unknown>
#16 0x55fc1536b262 <unknown>
#17 0x55fc1537cf34 <unknown>
#18 0x7f5f2e094ac3 <unknown>