2024-12-11 23:42:13 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/search
2024-12-11 23:42:13 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 306, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55f063e6931a <unknown>
#1 0x55f06397f6e0 <unknown>
#2 0x55f0639ce3e6 <unknown>
#3 0x55f0639ce681 <unknown>
#4 0x55f063a13b04 <unknown>
#5 0x55f0639f248d <unknown>
#6 0x55f063a10ed7 <unknown>
#7 0x55f0639f2203 <unknown>
#8 0x55f0639c0cc0 <unknown>
#9 0x55f0639c1c9e <unknown>
#10 0x55f063e36d0b <unknown>
#11 0x55f063e3ac92 <unknown>
#12 0x55f063e23b3c <unknown>
#13 0x55f063e3b807 <unknown>
#14 0x55f063e090df <unknown>
#15 0x55f063e58578 <unknown>
#16 0x55f063e58740 <unknown>
#17 0x55f063e68196 <unknown>
#18 0x7f95cc494ac3 <unknown>