2024-01-04 06:00:30 ERROR Unable to initialize WebDriver
2024-01-04 06:00:30 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 414, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5620b906af83 <unknown>
#1 0x5620b8d23cf7 <unknown>
#2 0x5620b8d7399e <unknown>
#3 0x5620b8d73aa1 <unknown>
#4 0x5620b8dbed64 <unknown>
#5 0x5620b8d9d0dd <unknown>
#6 0x5620b8dbc006 <unknown>
#7 0x5620b8d9ce53 <unknown>
#8 0x5620b8d64dd4 <unknown>
#9 0x5620b8d661de <unknown>
#10 0x5620b902f531 <unknown>
#11 0x5620b9033455 <unknown>
#12 0x5620b901bf55 <unknown>
#13 0x5620b90340ef <unknown>
#14 0x5620b8fff99f <unknown>
#15 0x5620b9058008 <unknown>
#16 0x5620b90581d7 <unknown>
#17 0x5620b906a124 <unknown>
#18 0x7f9009e94ac3 <unknown>

2024-01-04 06:00:40 ERROR Unable to initialize WebDriver
2024-01-04 06:00:40 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 414, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5620b906af83 <unknown>
#1 0x5620b8d23cf7 <unknown>
#2 0x5620b8d7399e <unknown>
#3 0x5620b8d73aa1 <unknown>
#4 0x5620b8dbed64 <unknown>
#5 0x5620b8d9d0dd <unknown>
#6 0x5620b8dbc006 <unknown>
#7 0x5620b8d9ce53 <unknown>
#8 0x5620b8d64dd4 <unknown>
#9 0x5620b8d661de <unknown>
#10 0x5620b902f531 <unknown>
#11 0x5620b9033455 <unknown>
#12 0x5620b901bf55 <unknown>
#13 0x5620b90340ef <unknown>
#14 0x5620b8fff99f <unknown>
#15 0x5620b9058008 <unknown>
#16 0x5620b90581d7 <unknown>
#17 0x5620b906a124 <unknown>
#18 0x7f9009e94ac3 <unknown>

2024-01-04 06:00:46 ERROR Unable to initialize WebDriver
2024-01-04 06:00:46 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 414, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5620b906af83 <unknown>
#1 0x5620b8d23cf7 <unknown>
#2 0x5620b8d7399e <unknown>
#3 0x5620b8d73aa1 <unknown>
#4 0x5620b8dbed64 <unknown>
#5 0x5620b8d9d0dd <unknown>
#6 0x5620b8dbc006 <unknown>
#7 0x5620b8d9ce53 <unknown>
#8 0x5620b8d64dd4 <unknown>
#9 0x5620b8d661de <unknown>
#10 0x5620b902f531 <unknown>
#11 0x5620b9033455 <unknown>
#12 0x5620b901bf55 <unknown>
#13 0x5620b90340ef <unknown>
#14 0x5620b8fff99f <unknown>
#15 0x5620b9058008 <unknown>
#16 0x5620b90581d7 <unknown>
#17 0x5620b906a124 <unknown>
#18 0x7f9009e94ac3 <unknown>