2023-12-28 15:42:11 ERROR Unable to initialize WebDriver
2023-12-28 15:42:11 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 412, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5558c937cf83 <unknown>
#1 0x5558c9035cf7 <unknown>
#2 0x5558c908599e <unknown>
#3 0x5558c9085aa1 <unknown>
#4 0x5558c90d0d64 <unknown>
#5 0x5558c90af0dd <unknown>
#6 0x5558c90ce006 <unknown>
#7 0x5558c90aee53 <unknown>
#8 0x5558c9076dd4 <unknown>
#9 0x5558c90781de <unknown>
#10 0x5558c9341531 <unknown>
#11 0x5558c9345455 <unknown>
#12 0x5558c932df55 <unknown>
#13 0x5558c93460ef <unknown>
#14 0x5558c931199f <unknown>
#15 0x5558c936a008 <unknown>
#16 0x5558c936a1d7 <unknown>
#17 0x5558c937c124 <unknown>
#18 0x7f4eca894ac3 <unknown>

2023-12-28 15:42:13 ERROR Unable to initialize WebDriver
2023-12-28 15:42:13 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 627, in wait_for_target_url
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2023-12-28 15:42:27 ERROR Unable to initialize WebDriver
2023-12-28 15:42:27 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 412, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5558c937cf83 <unknown>
#1 0x5558c9035cf7 <unknown>
#2 0x5558c908599e <unknown>
#3 0x5558c9085aa1 <unknown>
#4 0x5558c90d0d64 <unknown>
#5 0x5558c90af0dd <unknown>
#6 0x5558c90ce006 <unknown>
#7 0x5558c90aee53 <unknown>
#8 0x5558c9076dd4 <unknown>
#9 0x5558c90781de <unknown>
#10 0x5558c9341531 <unknown>
#11 0x5558c9345455 <unknown>
#12 0x5558c932df55 <unknown>
#13 0x5558c93460ef <unknown>
#14 0x5558c931199f <unknown>
#15 0x5558c936a008 <unknown>
#16 0x5558c936a1d7 <unknown>
#17 0x5558c937c124 <unknown>
#18 0x7f4eca894ac3 <unknown>