2024-03-01 08:00:23 ERROR Elements not present after 0.5 seconds on page: https://capital.com/
2024-03-01 08:00:23 ERROR Can't see element by locator ('css selector', "iframe[title='reCAPTCHA']")
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 518, in is_captcha
    if self.elements_are_visible(Captcha.CAPTCHA_IFRAME):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 638, in elements_are_visible
    return Wait(self.driver, timeout).until(EC.visibility_of_any_elements_located(locator),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Can't see element by locator ('css selector', "iframe[title='reCAPTCHA']")

2024-03-01 08:00:48 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ru/torgovye-strategii
2024-03-01 08:00:48 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 302, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5608e1fa9e93 <unknown>
#1 0x5608e1ca1ce6 <unknown>
#2 0x5608e1cece48 <unknown>
#3 0x5608e1cecf01 <unknown>
#4 0x5608e1d303f4 <unknown>
#5 0x5608e1d0eedd <unknown>
#6 0x5608e1d2d899 <unknown>
#7 0x5608e1d0ec53 <unknown>
#8 0x5608e1cdfdb3 <unknown>
#9 0x5608e1ce077e <unknown>
#10 0x5608e1f6f7cb <unknown>
#11 0x5608e1f737e5 <unknown>
#12 0x5608e1f5d0e1 <unknown>
#13 0x5608e1f74372 <unknown>
#14 0x5608e1f411bf <unknown>
#15 0x5608e1f98488 <unknown>
#16 0x5608e1f98683 <unknown>
#17 0x5608e1fa9044 <unknown>
#18 0x7f2e8c694ac3 <unknown>

2024-03-01 08:00:51 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ru/torgovye-strategii
2024-03-01 08:00:51 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 302, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5608e1fa9e93 <unknown>
#1 0x5608e1ca1ce6 <unknown>
#2 0x5608e1cece48 <unknown>
#3 0x5608e1cecf01 <unknown>
#4 0x5608e1d303f4 <unknown>
#5 0x5608e1d0eedd <unknown>
#6 0x5608e1d2d899 <unknown>
#7 0x5608e1d0ec53 <unknown>
#8 0x5608e1cdfdb3 <unknown>
#9 0x5608e1ce077e <unknown>
#10 0x5608e1f6f7cb <unknown>
#11 0x5608e1f737e5 <unknown>
#12 0x5608e1f5d0e1 <unknown>
#13 0x5608e1f74372 <unknown>
#14 0x5608e1f411bf <unknown>
#15 0x5608e1f98488 <unknown>
#16 0x5608e1f98683 <unknown>
#17 0x5608e1fa9044 <unknown>
#18 0x7f2e8c694ac3 <unknown>

2024-03-01 08:00:54 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ru/torgovye-strategii
2024-03-01 08:00:54 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 302, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5608e1fa9e93 <unknown>
#1 0x5608e1ca1ce6 <unknown>
#2 0x5608e1cece48 <unknown>
#3 0x5608e1cecf01 <unknown>
#4 0x5608e1d303f4 <unknown>
#5 0x5608e1d0eedd <unknown>
#6 0x5608e1d2d899 <unknown>
#7 0x5608e1d0ec53 <unknown>
#8 0x5608e1cdfdb3 <unknown>
#9 0x5608e1ce077e <unknown>
#10 0x5608e1f6f7cb <unknown>
#11 0x5608e1f737e5 <unknown>
#12 0x5608e1f5d0e1 <unknown>
#13 0x5608e1f74372 <unknown>
#14 0x5608e1f411bf <unknown>
#15 0x5608e1f98488 <unknown>
#16 0x5608e1f98683 <unknown>
#17 0x5608e1fa9044 <unknown>
#18 0x7f2e8c694ac3 <unknown>