2024-04-03 15:49:35 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ru/torgovlya-cfd-serebro
2024-04-03 15:49:35 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560cd86be8a3 <unknown>
#1 0x560cd83b48c6 <unknown>
#2 0x560cd83ff618 <unknown>
#3 0x560cd83ff6d1 <unknown>
#4 0x560cd8442744 <unknown>
#5 0x560cd84215cd <unknown>
#6 0x560cd843fc19 <unknown>
#7 0x560cd8421343 <unknown>
#8 0x560cd83f2593 <unknown>
#9 0x560cd83f2f5e <unknown>
#10 0x560cd868288b <unknown>
#11 0x560cd86867e5 <unknown>
#12 0x560cd86705b1 <unknown>
#13 0x560cd8687372 <unknown>
#14 0x560cd86558bf <unknown>
#15 0x560cd86ad768 <unknown>
#16 0x560cd86ad93b <unknown>
#17 0x560cd86bd9f4 <unknown>
#18 0x7f6bffe94ac3 <unknown>

2024-04-03 15:49:39 ERROR Elements not present after 0.5 seconds on page: https://capital.com/
2024-04-03 15:49:39 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560cd86be8a3 <unknown>
#1 0x560cd83b48c6 <unknown>
#2 0x560cd83ff618 <unknown>
#3 0x560cd83ff6d1 <unknown>
#4 0x560cd8442744 <unknown>
#5 0x560cd84215cd <unknown>
#6 0x560cd843fc19 <unknown>
#7 0x560cd8421343 <unknown>
#8 0x560cd83f2593 <unknown>
#9 0x560cd83f2f5e <unknown>
#10 0x560cd868288b <unknown>
#11 0x560cd86867e5 <unknown>
#12 0x560cd86705b1 <unknown>
#13 0x560cd8687372 <unknown>
#14 0x560cd86558bf <unknown>
#15 0x560cd86ad768 <unknown>
#16 0x560cd86ad93b <unknown>
#17 0x560cd86bd9f4 <unknown>
#18 0x7f6bffe94ac3 <unknown>

2024-04-03 15:49:42 ERROR Elements not present after 0.5 seconds on page: https://capital.com/
2024-04-03 15:49:42 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560cd86be8a3 <unknown>
#1 0x560cd83b48c6 <unknown>
#2 0x560cd83ff618 <unknown>
#3 0x560cd83ff6d1 <unknown>
#4 0x560cd8442744 <unknown>
#5 0x560cd84215cd <unknown>
#6 0x560cd843fc19 <unknown>
#7 0x560cd8421343 <unknown>
#8 0x560cd83f2593 <unknown>
#9 0x560cd83f2f5e <unknown>
#10 0x560cd868288b <unknown>
#11 0x560cd86867e5 <unknown>
#12 0x560cd86705b1 <unknown>
#13 0x560cd8687372 <unknown>
#14 0x560cd86558bf <unknown>
#15 0x560cd86ad768 <unknown>
#16 0x560cd86ad93b <unknown>
#17 0x560cd86bd9f4 <unknown>
#18 0x7f6bffe94ac3 <unknown>

2024-04-03 15:49:46 ERROR Elements not present after 0.5 seconds on page: https://capital.com/
2024-04-03 15:49:46 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560cd86be8a3 <unknown>
#1 0x560cd83b48c6 <unknown>
#2 0x560cd83ff618 <unknown>
#3 0x560cd83ff6d1 <unknown>
#4 0x560cd8442744 <unknown>
#5 0x560cd84215cd <unknown>
#6 0x560cd843fc19 <unknown>
#7 0x560cd8421343 <unknown>
#8 0x560cd83f2593 <unknown>
#9 0x560cd83f2f5e <unknown>
#10 0x560cd868288b <unknown>
#11 0x560cd86867e5 <unknown>
#12 0x560cd86705b1 <unknown>
#13 0x560cd8687372 <unknown>
#14 0x560cd86558bf <unknown>
#15 0x560cd86ad768 <unknown>
#16 0x560cd86ad93b <unknown>
#17 0x560cd86bd9f4 <unknown>
#18 0x7f6bffe94ac3 <unknown>