2025-05-10 02:53:19 ERROR Elements not present after 0.5 seconds on page: https://capital.com/en-gb
2025-05-10 02:53:19 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 340, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55dcecbc278a <unknown>
#1 0x55dcec6650a0 <unknown>
#2 0x55dcec6b69b0 <unknown>
#3 0x55dcec6b6ba1 <unknown>
#4 0x55dcec704ea4 <unknown>
#5 0x55dcec6dc3cd <unknown>
#6 0x55dcec7022a0 <unknown>
#7 0x55dcec6dc173 <unknown>
#8 0x55dcec6a8d4b <unknown>
#9 0x55dcec6a99b1 <unknown>
#10 0x55dcecb8793b <unknown>
#11 0x55dcecb8b83a <unknown>
#12 0x55dcecb6f692 <unknown>
#13 0x55dcecb8c3c4 <unknown>
#14 0x55dcecb544cf <unknown>
#15 0x55dcecbb0568 <unknown>
#16 0x55dcecbb0746 <unknown>
#17 0x55dcecbc15f6 <unknown>
#18 0x7f123089caa4 <unknown>
#19 0x7f1230929c3c <unknown>

2025-05-10 02:53:30 ERROR Elements not present after 0.5 seconds on page: https://capital.com/en-au
2025-05-10 02:53:30 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 340, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55dcecbc278a <unknown>
#1 0x55dcec6650a0 <unknown>
#2 0x55dcec6b69b0 <unknown>
#3 0x55dcec6b6ba1 <unknown>
#4 0x55dcec704ea4 <unknown>
#5 0x55dcec6dc3cd <unknown>
#6 0x55dcec7022a0 <unknown>
#7 0x55dcec6dc173 <unknown>
#8 0x55dcec6a8d4b <unknown>
#9 0x55dcec6a99b1 <unknown>
#10 0x55dcecb8793b <unknown>
#11 0x55dcecb8b83a <unknown>
#12 0x55dcecb6f692 <unknown>
#13 0x55dcecb8c3c4 <unknown>
#14 0x55dcecb544cf <unknown>
#15 0x55dcecbb0568 <unknown>
#16 0x55dcecbb0746 <unknown>
#17 0x55dcecbc15f6 <unknown>
#18 0x7f123089caa4 <unknown>
#19 0x7f1230929c3c <unknown>