2024-03-21 05:18:17 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/principales-indices-mundiales?t=most
2024-03-21 05:18:17 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 303, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562fb1849f33 <unknown>
#1 0x562fb1541ce6 <unknown>
#2 0x562fb158ce48 <unknown>
#3 0x562fb158cf01 <unknown>
#4 0x562fb15d03f4 <unknown>
#5 0x562fb15aeedd <unknown>
#6 0x562fb15cd899 <unknown>
#7 0x562fb15aec53 <unknown>
#8 0x562fb157fdb3 <unknown>
#9 0x562fb158077e <unknown>
#10 0x562fb180f86b <unknown>
#11 0x562fb1813885 <unknown>
#12 0x562fb17fd181 <unknown>
#13 0x562fb1814412 <unknown>
#14 0x562fb17e125f <unknown>
#15 0x562fb1838528 <unknown>
#16 0x562fb1838723 <unknown>
#17 0x562fb18490e4 <unknown>
#18 0x7f609d294ac3 <unknown>