2024-07-20 04:24:40 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ar/search
2024-07-20 04:24:40 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559f4b5c7c5a <unknown>
#1 0x559f4b2aae2c <unknown>
#2 0x559f4b2f7661 <unknown>
#3 0x559f4b2f7751 <unknown>
#4 0x559f4b33bf64 <unknown>
#5 0x559f4b31a5ed <unknown>
#6 0x559f4b339303 <unknown>
#7 0x559f4b31a363 <unknown>
#8 0x559f4b2ea247 <unknown>
#9 0x559f4b2eab9e <unknown>
#10 0x559f4b58e22b <unknown>
#11 0x559f4b5922d1 <unknown>
#12 0x559f4b579ade <unknown>
#13 0x559f4b592e32 <unknown>
#14 0x559f4b55e77f <unknown>
#15 0x559f4b5b7618 <unknown>
#16 0x559f4b5b77f0 <unknown>
#17 0x559f4b5c6d8c <unknown>
#18 0x7fd9a0894ac3 <unknown>