2024-04-04 10:54:56 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/trade-forex
2024-04-04 10:54:56 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55845b1888a3 <unknown>
#1 0x55845ae7e8c6 <unknown>
#2 0x55845aec9618 <unknown>
#3 0x55845aec96d1 <unknown>
#4 0x55845af0c744 <unknown>
#5 0x55845aeeb5cd <unknown>
#6 0x55845af09c19 <unknown>
#7 0x55845aeeb343 <unknown>
#8 0x55845aebc593 <unknown>
#9 0x55845aebcf5e <unknown>
#10 0x55845b14c88b <unknown>
#11 0x55845b1507e5 <unknown>
#12 0x55845b13a5b1 <unknown>
#13 0x55845b151372 <unknown>
#14 0x55845b11f8bf <unknown>
#15 0x55845b177768 <unknown>
#16 0x55845b17793b <unknown>
#17 0x55845b1879f4 <unknown>
#18 0x7f913d094ac3 <unknown>

2024-04-04 10:55:00 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/trade-forex
2024-04-04 10:55:00 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55845b1888a3 <unknown>
#1 0x55845ae7e8c6 <unknown>
#2 0x55845aec9618 <unknown>
#3 0x55845aec96d1 <unknown>
#4 0x55845af0c744 <unknown>
#5 0x55845aeeb5cd <unknown>
#6 0x55845af09c19 <unknown>
#7 0x55845aeeb343 <unknown>
#8 0x55845aebc593 <unknown>
#9 0x55845aebcf5e <unknown>
#10 0x55845b14c88b <unknown>
#11 0x55845b1507e5 <unknown>
#12 0x55845b13a5b1 <unknown>
#13 0x55845b151372 <unknown>
#14 0x55845b11f8bf <unknown>
#15 0x55845b177768 <unknown>
#16 0x55845b17793b <unknown>
#17 0x55845b1879f4 <unknown>
#18 0x7f913d094ac3 <unknown>

2024-04-04 10:55:03 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/trade-forex
2024-04-04 10:55:03 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55845b1888a3 <unknown>
#1 0x55845ae7e8c6 <unknown>
#2 0x55845aec9618 <unknown>
#3 0x55845aec96d1 <unknown>
#4 0x55845af0c744 <unknown>
#5 0x55845aeeb5cd <unknown>
#6 0x55845af09c19 <unknown>
#7 0x55845aeeb343 <unknown>
#8 0x55845aebc593 <unknown>
#9 0x55845aebcf5e <unknown>
#10 0x55845b14c88b <unknown>
#11 0x55845b1507e5 <unknown>
#12 0x55845b13a5b1 <unknown>
#13 0x55845b151372 <unknown>
#14 0x55845b11f8bf <unknown>
#15 0x55845b177768 <unknown>
#16 0x55845b17793b <unknown>
#17 0x55845b1879f4 <unknown>
#18 0x7f913d094ac3 <unknown>

2024-04-04 10:55:06 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/trade-forex
2024-04-04 10:55:06 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55845b1888a3 <unknown>
#1 0x55845ae7e8c6 <unknown>
#2 0x55845aec9618 <unknown>
#3 0x55845aec96d1 <unknown>
#4 0x55845af0c744 <unknown>
#5 0x55845aeeb5cd <unknown>
#6 0x55845af09c19 <unknown>
#7 0x55845aeeb343 <unknown>
#8 0x55845aebc593 <unknown>
#9 0x55845aebcf5e <unknown>
#10 0x55845b14c88b <unknown>
#11 0x55845b1507e5 <unknown>
#12 0x55845b13a5b1 <unknown>
#13 0x55845b151372 <unknown>
#14 0x55845b11f8bf <unknown>
#15 0x55845b177768 <unknown>
#16 0x55845b17793b <unknown>
#17 0x55845b1879f4 <unknown>
#18 0x7f913d094ac3 <unknown>