2024-03-25 12:56:02 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/cotton-no-2-spot-commodity
2024-03-25 12:56:02 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 306, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562f85ae5f33 <unknown>
#1 0x562f857ddce6 <unknown>
#2 0x562f85828e48 <unknown>
#3 0x562f85828f01 <unknown>
#4 0x562f8586c3f4 <unknown>
#5 0x562f8584aedd <unknown>
#6 0x562f85869899 <unknown>
#7 0x562f8584ac53 <unknown>
#8 0x562f8581bdb3 <unknown>
#9 0x562f8581c77e <unknown>
#10 0x562f85aab86b <unknown>
#11 0x562f85aaf885 <unknown>
#12 0x562f85a99181 <unknown>
#13 0x562f85ab0412 <unknown>
#14 0x562f85a7d25f <unknown>
#15 0x562f85ad4528 <unknown>
#16 0x562f85ad4723 <unknown>
#17 0x562f85ae50e4 <unknown>
#18 0x7f8539a94ac3 <unknown>

2024-03-25 12:56:06 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/cotton-no-2-spot-commodity
2024-03-25 12:56:06 ERROR Can't click element by locator ('css selector', '#s_overlay button.s_cancel')
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/Elements/PageInstrumentViewDetailedChartButton.py", line 67, in element_click
    button_list[0].click()
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="/cn/cotton-no-2-spot-commodity#" data-link="uu" data-iid="7090561509053636" data-platform="spotlight" class="chartMarketsFunc__btn js_signup_new js-analyticsVisible js-analyticsClick" data-type="detailed_chart">...</a> is not clickable at point (221, 361). Other element would receive the click: <div class="onetrust-pc-dark-filter ot-fade-in" style="z-index:2147483645;"></div>
  (Session info: chrome=122.0.6261.128)
Stacktrace:
#0 0x562f85ae5f33 <unknown>
#1 0x562f857ddce6 <unknown>
#2 0x562f8582fa73 <unknown>
#3 0x562f8582d98e <unknown>
#4 0x562f8582b367 <unknown>
#5 0x562f8582a732 <unknown>
#6 0x562f8581dd27 <unknown>
#7 0x562f8584aeb2 <unknown>
#8 0x562f8581d6b8 <unknown>
#9 0x562f8584b07e <unknown>
#10 0x562f85869899 <unknown>
#11 0x562f8584ac53 <unknown>
#12 0x562f8581bdb3 <unknown>
#13 0x562f8581c77e <unknown>
#14 0x562f85aab86b <unknown>
#15 0x562f85aaf885 <unknown>
#16 0x562f85a99181 <unknown>
#17 0x562f85ab0412 <unknown>
#18 0x562f85a7d25f <unknown>
#19 0x562f85ad4528 <unknown>
#20 0x562f85ad4723 <unknown>
#21 0x562f85ae50e4 <unknown>
#22 0x7f8539a94ac3 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 346, in element_is_clickable
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Can't click element by locator ('css selector', '#s_overlay button.s_cancel')
Stacktrace:
#0 0x562f85ae5f33 <unknown>
#1 0x562f857ddce6 <unknown>
#2 0x562f85828e48 <unknown>
#3 0x562f85828f01 <unknown>
#4 0x562f8586c3f4 <unknown>
#5 0x562f8584aedd <unknown>
#6 0x562f85869899 <unknown>
#7 0x562f8584ac53 <unknown>
#8 0x562f8581bdb3 <unknown>
#9 0x562f8581c77e <unknown>
#10 0x562f85aab86b <unknown>
#11 0x562f85aaf885 <unknown>
#12 0x562f85a99181 <unknown>
#13 0x562f85ab0412 <unknown>
#14 0x562f85a7d25f <unknown>
#15 0x562f85ad4528 <unknown>
#16 0x562f85ad4723 <unknown>
#17 0x562f85ae50e4 <unknown>
#18 0x7f8539a94ac3 <unknown>