2024-04-04 09:13:39 ERROR Elements not present after 0.5 seconds on page: https://capital.com/it/trading-su-azioni
2024-04-04 09:13:39 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5578aee688a3 <unknown>
#1 0x5578aeb5e8c6 <unknown>
#2 0x5578aeba9618 <unknown>
#3 0x5578aeba96d1 <unknown>
#4 0x5578aebec744 <unknown>
#5 0x5578aebcb5cd <unknown>
#6 0x5578aebe9c19 <unknown>
#7 0x5578aebcb343 <unknown>
#8 0x5578aeb9c593 <unknown>
#9 0x5578aeb9cf5e <unknown>
#10 0x5578aee2c88b <unknown>
#11 0x5578aee307e5 <unknown>
#12 0x5578aee1a5b1 <unknown>
#13 0x5578aee31372 <unknown>
#14 0x5578aedff8bf <unknown>
#15 0x5578aee57768 <unknown>
#16 0x5578aee5793b <unknown>
#17 0x5578aee679f4 <unknown>
#18 0x7fb74be94ac3 <unknown>

2024-04-04 09:13:46 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-04 09:13:46 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5578aee688a3 <unknown>
#1 0x5578aeb5e8c6 <unknown>
#2 0x5578aeba9618 <unknown>
#3 0x5578aeba96d1 <unknown>
#4 0x5578aebec744 <unknown>
#5 0x5578aebcb5cd <unknown>
#6 0x5578aebe9c19 <unknown>
#7 0x5578aebcb343 <unknown>
#8 0x5578aeb9c593 <unknown>
#9 0x5578aeb9cf5e <unknown>
#10 0x5578aee2c88b <unknown>
#11 0x5578aee307e5 <unknown>
#12 0x5578aee1a5b1 <unknown>
#13 0x5578aee31372 <unknown>
#14 0x5578aedff8bf <unknown>
#15 0x5578aee57768 <unknown>
#16 0x5578aee5793b <unknown>
#17 0x5578aee679f4 <unknown>
#18 0x7fb74be94ac3 <unknown>

2024-04-04 09:13:49 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-04 09:13:49 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5578aee688a3 <unknown>
#1 0x5578aeb5e8c6 <unknown>
#2 0x5578aeba9618 <unknown>
#3 0x5578aeba96d1 <unknown>
#4 0x5578aebec744 <unknown>
#5 0x5578aebcb5cd <unknown>
#6 0x5578aebe9c19 <unknown>
#7 0x5578aebcb343 <unknown>
#8 0x5578aeb9c593 <unknown>
#9 0x5578aeb9cf5e <unknown>
#10 0x5578aee2c88b <unknown>
#11 0x5578aee307e5 <unknown>
#12 0x5578aee1a5b1 <unknown>
#13 0x5578aee31372 <unknown>
#14 0x5578aedff8bf <unknown>
#15 0x5578aee57768 <unknown>
#16 0x5578aee5793b <unknown>
#17 0x5578aee679f4 <unknown>
#18 0x7fb74be94ac3 <unknown>

2024-04-04 09:13:52 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-04 09:13:52 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 307, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5578aee688a3 <unknown>
#1 0x5578aeb5e8c6 <unknown>
#2 0x5578aeba9618 <unknown>
#3 0x5578aeba96d1 <unknown>
#4 0x5578aebec744 <unknown>
#5 0x5578aebcb5cd <unknown>
#6 0x5578aebe9c19 <unknown>
#7 0x5578aebcb343 <unknown>
#8 0x5578aeb9c593 <unknown>
#9 0x5578aeb9cf5e <unknown>
#10 0x5578aee2c88b <unknown>
#11 0x5578aee307e5 <unknown>
#12 0x5578aee1a5b1 <unknown>
#13 0x5578aee31372 <unknown>
#14 0x5578aedff8bf <unknown>
#15 0x5578aee57768 <unknown>
#16 0x5578aee5793b <unknown>
#17 0x5578aee679f4 <unknown>
#18 0x7fb74be94ac3 <unknown>