2024-02-16 13:55:13 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trade-etfs
2024-02-16 13:55:13 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55ee756f6d93 <unknown>
#1 0x55ee753da337 <unknown>
#2 0x55ee75425d60 <unknown>
#3 0x55ee75425e51 <unknown>
#4 0x55ee75469bc4 <unknown>
#5 0x55ee7544846d <unknown>
#6 0x55ee7546712d <unknown>
#7 0x55ee754481e3 <unknown>
#8 0x55ee75418135 <unknown>
#9 0x55ee7541913e <unknown>
#10 0x55ee756bae4b <unknown>
#11 0x55ee756bedfa <unknown>
#12 0x55ee756a76d5 <unknown>
#13 0x55ee756bfa6f <unknown>
#14 0x55ee7568b69f <unknown>
#15 0x55ee756e4098 <unknown>
#16 0x55ee756e4262 <unknown>
#17 0x55ee756f5f34 <unknown>
#18 0x7fbf0f094ac3 <unknown>

2024-02-16 13:55:17 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trade-etfs
2024-02-16 13:55:17 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55ee756f6d93 <unknown>
#1 0x55ee753da337 <unknown>
#2 0x55ee75425d60 <unknown>
#3 0x55ee75425e51 <unknown>
#4 0x55ee75469bc4 <unknown>
#5 0x55ee7544846d <unknown>
#6 0x55ee7546712d <unknown>
#7 0x55ee754481e3 <unknown>
#8 0x55ee75418135 <unknown>
#9 0x55ee7541913e <unknown>
#10 0x55ee756bae4b <unknown>
#11 0x55ee756bedfa <unknown>
#12 0x55ee756a76d5 <unknown>
#13 0x55ee756bfa6f <unknown>
#14 0x55ee7568b69f <unknown>
#15 0x55ee756e4098 <unknown>
#16 0x55ee756e4262 <unknown>
#17 0x55ee756f5f34 <unknown>
#18 0x7fbf0f094ac3 <unknown>